/* This file was auto-generated by KreMLin! */

#include "Hacl_VRF_Lib.h"

uint64_t *Hacl_VRF_Lib_getx(uint64_t *p)
{
  return p;
}

uint64_t *Hacl_VRF_Lib_gety(uint64_t *p)
{
  return p + (uint32_t)5U;
}

uint64_t *Hacl_VRF_Lib_getz(uint64_t *p)
{
  return p + (uint32_t)10U;
}

uint64_t *Hacl_VRF_Lib_gett(uint64_t *p)
{
  return p + (uint32_t)15U;
}

