/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_VRF_DecodeProof_H
#define __Hacl_VRF_DecodeProof_H


#include "Hacl_VRF_Lib.h"
#include "Hacl_VRF_HashPoints.h"
#include "Hacl_VRF_HashToCurveFinal.h"
#include "testlib.h"

bool Hacl_VRF_DecodeProof_decodeProof(uint64_t *gamma, uint8_t *c, uint8_t *s, uint8_t *proof);
#endif
