/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_VRF_HashVerify_H
#define __Hacl_VRF_HashVerify_H


#include "Hacl_VRF_Lib.h"
#include "Hacl_VRF_HashPoints.h"
#include "Hacl_VRF_HashToCurveFinal.h"
#include "Hacl_VRF_DecodeProof.h"
#include "Hacl_VRF_Hash.h"
#include "testlib.h"

void
Hacl_VRF_HashVerify_point_sum(
  uint64_t *pointTo0,
  uint64_t *pointTo1,
  uint64_t *pointTo2,
  uint64_t *pointFrom0,
  uint8_t *scalarFrom0,
  uint64_t *pointFrom1,
  uint8_t *scalarFrom1
);

bool
Hacl_VRF_HashVerify__ECVRF_verify(
  Prims_nat len,
  uint8_t *proof,
  uint32_t inputLength,
  uint8_t *input,
  uint64_t *pk
);
#endif
