/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_VRF_ProofToHash_H
#define __Hacl_VRF_ProofToHash_H


#include "Hacl_VRF_Lib.h"
#include "Hacl_VRF_HashPoints.h"
#include "Hacl_VRF_HashToCurveFinal.h"
#include "Hacl_VRF_DecodeProof.h"
#include "Hacl_VRF_Hash.h"
#include "Hacl_VRF_HashVerify.h"
#include "testlib.h"

bool Hacl_VRF_ProofToHash_partialDecodeProof(uint64_t *gamma, uint8_t *proof);

bool Hacl_VRF_ProofToHash_proofToHash(uint8_t *beta, uint8_t *proof);
#endif
