/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_VRF_HashToCurveFinal_H
#define __Hacl_VRF_HashToCurveFinal_H


#include "Hacl_VRF_Lib.h"
#include "Hacl_VRF_HashPoints.h"
#include "testlib.h"

void Hacl_VRF_HashToCurveFinal_toU8(uint8_t *out, uint32_t input);

bool Hacl_VRF_HashToCurveFinal_isNotPointAtInfinity(uint64_t *p);

void Hacl_VRF_HashToCurveFinal_pointMult8(uint64_t *out, uint64_t *p);

bool
Hacl_VRF_HashToCurveFinal__helper_ECVRF_hash_to_curve(
  Prims_nat len,
  uint64_t *pointBuffer,
  uint8_t *output,
  uint32_t clen,
  uint32_t counter,
  uint64_t *pointTemporary
);

bool
Hacl_VRF_HashToCurveFinal__ECVRF_hash_to_curve(
  Prims_nat len,
  uint64_t *pointBuffer,
  uint64_t *publicKey,
  uint32_t clen,
  uint8_t *input
);
#endif
