/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_VRF_Hash_H
#define __Hacl_VRF_Hash_H


#include "Hacl_VRF_Lib.h"
#include "Hacl_VRF_HashPoints.h"
#include "Hacl_VRF_HashToCurveFinal.h"
#include "Hacl_VRF_DecodeProof.h"
#include "testlib.h"

bool Hacl_VRF_Hash__ECVRF_prove_2(uint8_t *proof, uint8_t *secret);

bool
Hacl_VRF_Hash__ECVRF_prove(
  Prims_nat len,
  uint8_t *proof,
  uint32_t inputLength,
  uint8_t *input,
  uint8_t *secret,
  uint64_t *pk
);
#endif
