/* This file was auto-generated by KreMLin! */

#include "Hacl_VRF_HashVerify.h"

void
Hacl_VRF_HashVerify_point_sum(
  uint64_t *pointTo0,
  uint64_t *pointTo1,
  uint64_t *pointTo2,
  uint64_t *pointFrom0,
  uint8_t *scalarFrom0,
  uint64_t *pointFrom1,
  uint8_t *scalarFrom1
)
{
  Hacl_VRF_Lib_point_mult(pointTo0, pointFrom0, scalarFrom0);
  Hacl_VRF_Lib_point_mult(pointTo1, pointFrom1, scalarFrom1);
  Hacl_VRF_Lib_point_add(pointTo2, pointTo0, pointTo1);
}

bool
Hacl_VRF_HashVerify__ECVRF_verify(
  Prims_nat len,
  uint8_t *proof,
  uint32_t inputLength,
  uint8_t *input,
  uint64_t *pk
)
{
  uint64_t buf[200U] = { 0U };
  uint64_t *pubKey = buf + (uint32_t)40U;
  for (uint32_t i = (uint32_t)0U; i < (uint32_t)20U; i = i + (uint32_t)1U)
  {
    uint64_t src_i = pk[i];
    pubKey[i] = src_i;
  }
  uint8_t buf1[64U] = { 0U };
  uint64_t *generator = buf;
  uint64_t *h = buf + (uint32_t)20U;
  uint64_t *pk1 = buf + (uint32_t)40U;
  uint64_t *gamma = buf + (uint32_t)60U;
  uint64_t *u = buf + (uint32_t)80U;
  uint64_t *v1 = buf + (uint32_t)100U;
  uint64_t *bufferToHash = buf;
  uint64_t *yc = buf + (uint32_t)120U;
  uint64_t *gs = buf + (uint32_t)140U;
  uint64_t *gammac = buf + (uint32_t)160U;
  uint64_t *hs = buf + (uint32_t)180U;
  uint8_t *gamma_ = proof;
  uint8_t *c = proof + (uint32_t)32U;
  uint8_t *s = proof + (uint32_t)48U;
  bool r0 = Hacl_VRF_Lib_decompress(gamma, gamma_);
  bool r;
  if (!r0)
    r = false;
  else
  {
    uint8_t *cExtended = buf1;
    uint8_t *cToCheck = buf1 + (uint32_t)32U;
    uint8_t *partOfExtended = buf1;
    for (uint32_t i = (uint32_t)0U; i < (uint32_t)16U; i = i + (uint32_t)1U)
    {
      uint8_t src_i = c[i];
      partOfExtended[i] = src_i;
    }
    Hacl_VRF_Lib_make_g(generator);
    Hacl_VRF_HashVerify_point_sum(yc, gs, u, pk1, cExtended, generator, s);
    bool r1 = Hacl_VRF_HashToCurveFinal__ECVRF_hash_to_curve(len, h, pk1, inputLength, input);
    bool ite;
    if (!r1)
      ite = false;
    else
    {
      Hacl_VRF_HashVerify_point_sum(gammac, hs, v1, gamma, cExtended, h, s);
      Hacl_VRF_HashPoints__ECVRF_hashPoints(cToCheck, bufferToHash);
      uint8_t *cToCheckLow = cToCheck + (uint32_t)16U;
      bool r2 = Hacl_VRF_Lib_equalBuffer((krml_checked_int_t)16, cToCheckLow, c);
      ite = r2;
    }
    r = ite;
  }
  bool r_ = r;
  bool r1 = r_;
  return r1;
}

