/* This file was auto-generated by KreMLin! */

#include "Hacl_VRF_HashPoints.h"

void Hacl_VRF_HashPoints__ECVRF_hashPoints(uint8_t *hashBuffer, uint64_t *points)
{
  uint32_t size_hash = (uint32_t)192U;
  KRML_CHECK_SIZE((uint8_t)0U, size_hash);
  uint8_t buf[size_hash];
  memset(buf, 0U, size_hash * sizeof buf[0U]);
  uint64_t *pointA = points;
  uint64_t *pointB = points + (uint32_t)20U;
  uint64_t *pointC = points + (uint32_t)40U;
  uint64_t *pointE = points + (uint32_t)80U;
  uint64_t *pointF = points + (uint32_t)100U;
  Hacl_VRF_HashPoints_compress(buf, pointA);
  Hacl_VRF_HashPoints_compress(buf + (uint32_t)32U, pointB);
  Hacl_VRF_HashPoints_compress(buf + (uint32_t)64U, pointC);
  Hacl_VRF_HashPoints_compress(buf + (uint32_t)96U, pointC);
  Hacl_VRF_HashPoints_compress(buf + (uint32_t)128U, pointE);
  Hacl_VRF_HashPoints_compress(buf + (uint32_t)160U, pointF);
  Hacl_VRF_HashPoints_hash(hashBuffer, size_hash, buf);
}

