/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __Hacl_VRF_HashPoints_H
#define __Hacl_VRF_HashPoints_H


#include "Hacl_VRF_Lib.h"
#include "testlib.h"

extern void Hacl_VRF_HashPoints_compress(uint8_t *x0, uint64_t *x1);

extern void Hacl_VRF_HashPoints_hash(uint8_t *x0, uint32_t x1, uint8_t *x2);

void Hacl_VRF_HashPoints__ECVRF_hashPoints(uint8_t *hashBuffer, uint64_t *points);
#endif
